function [beta,resnorm] = fitUNIQUACglGlobalParameters( ...
    systems,...
    antoine,...
    gE,...
    beta,...
    c_ij,...
    config,...
    options)
%FITGLOBALPARAMETERS Fit global beta parameters.

%% Build model input

modelInput = struct();

modelInput.antoine = antoine;

gE.c_ij = c_ij;

modelInput.uniquac_gl = gE;


%% Optimization

[beta,resnorm] = lsqnonlin( ...
    @(beta) global_objective( ...
        beta,...
        systems,...
        modelInput), ...
    beta,...
    config.beta_i_lb,...
    config.beta_i_ub,...
    options);

end