function c_ij = fitUNIQUACglBinaryParameters( ...
    systems,...
    antoine,...
    gE,...
    beta,...
    c_ij,...
    config,...
    options)

%FITBINARYPARAMETERS Fit binary interaction parameters c_ij.

%% Loop over prepared binary systems

for s = 1:numel(systems)

    data = systems(s);

    id = data.id;

    fprintf("Fit c_ij: %s\n", data.name);


    %% Pure component parameters

    modelInput = struct();
    modelInput.func = config.func;
    modelInput.name = func2str(config.func);
    modelInput.A = antoine.A(id);
    modelInput.B = antoine.B(id);
    modelInput.C = antoine.C(id);
    modelInput.r = gE.r_i(id);
    modelInput.q = gE.q_i(id);
    modelInput.beta_i = beta(id);

    %% Fit binary parameter

    k = id(1);
    l = id(2);

    c_ij(k,l) = lsqnonlin( ...
        @(c)local_objective( ...
            c,...
            data.T,...
            data.x,...
            data.y,...
            data.P,...
            modelInput),...
        c_ij(k,l),...
        config.c_ij_lb(k,l),...
        config.c_ij_ub(k,l),...
        options);

end

end