function plotVLESystem(selectedSystem,...
    modelInput)


%% Plot style

style = plotSettings();


%% Extract system information


T_exp = selectedSystem.T;
x_exp = selectedSystem.x;
y_exp = selectedSystem.y;
P_exp = selectedSystem.P;

A = modelInput.antoine.A;
B = modelInput.antoine.B;
C = modelInput.antoine.C;
modelName = modelInput.model_name;

%% Create figure

%T-xy plot
figure;
ax = axes();
hold on
box on

xlabel("{\it x_1}, {\it y_1}")
ylabel("{\it T} / K")

set(ax,...
    "FontSize",style.fontSize,"LineWidth",2)
axis square
xlim([0 1])


%% Group pressure values

[P_sets,pressureGroup] = groupPressures(P_exp,500);


colors = lines(numel(P_sets));


%% Legend entries

plot(ax,NaN,NaN,...
    style.idealLineStyle,...
    "LineWidth",style.lineWidth,...
    "Color",'k',...
    "DisplayName","Ideal (Raoult)");

plot(ax,NaN,NaN,...
    style.modelLineStyle,...
    "LineWidth",style.lineWidth,...
    "Color",'k',...
    "DisplayName",formatModelName(modelName));

%% Loop over pressure levels
for j = 1:numel(P_sets)


    P_mean = P_sets(j);

    color = colors(j,:);

    %% Ideal model

    Tsat = T_Antoine(P_mean,A,B,C);

    T_id = linspace(Tsat(1),Tsat(2),200);

    x_id = zeros(size(T_id));
    y_id = zeros(size(T_id));


    for k = 1:numel(T_id)

        psat = p_Antoine(T_id(k),A,B,C);

        x_id(k)=...
            (P_mean-psat(2))/(psat(1)-psat(2));

        y_id(k)=...
            x_id(k)*psat(1)/P_mean;

    end

    plot(ax(1),x_id,T_id,...
        style.idealLineStyle,...
        "LineWidth",style.lineWidth,...
        "Color",color,...
        "HandleVisibility","off")


    plot(ax(1),y_id,T_id,...
        style.idealLineStyle,...
        "LineWidth",style.lineWidth,...
        "Color",color,...
        "HandleVisibility","off")



    %% gE model
    x_calc = eps:0.002:1;


    y_calc = zeros(size(x_calc));
    T_calc = zeros(size(x_calc));
    gamma_calc = zeros(numel(x_calc),2);

    for k = 1:numel(x_calc)


    [y_calc(k),T_calc(k),gamma_calc(k,:)] = ...
    bubble_point(P_mean,x_calc(k),modelInput);


    end

    %% Plot model
    
    plot(ax(1),x_calc,T_calc,...
        style.modelLineStyle,...
        "LineWidth",style.lineWidth,...
        "Color",color,...
        "HandleVisibility","off")


    plot(ax(1),y_calc,T_calc,...
        style.modelLineStyle,...
        "LineWidth",style.lineWidth,...
        "Color",color,...
        "HandleVisibility","off")

    

    % Activity coefficient plot
    figure;
    ax(j+1) = axes();
    hold on
    box on
    
    xlabel("{\it x_1}")
    ylabel("\it \gamma_i")
    
    set(ax(j+1),...
        "FontSize",style.fontSize,...
        "LineWidth",2)
    
    axis square
    xlim([0 1])

    hold on

    plot(ax(j+1),x_calc,gamma_calc(:,1),...
        style.modelLineStyle,...
        "LineWidth",style.lineWidth,...
        "Color",color,...
        "HandleVisibility","off")
    
    
    plot(ax(j+1),x_calc,gamma_calc(:,2),...
        style.modelLineStyle,...
        "LineWidth",style.lineWidth,...
        "Color",[0.6 0.6 0.6],...
        "HandleVisibility","off")

    %% Experimental points

    idx = pressureGroup == j;

    T_data = T_exp(idx);
    x_data = x_exp(idx);
    y_data = y_exp(idx);
    
    %% Experimental activity coefficients

    psat_exp = zeros(numel(T_data),2);
    
    gamma_exp = zeros(numel(T_data),2);
    
    
    for k = 1:numel(T_data)
    
        psat_exp(k,:) = p_Antoine( ...
            T_data(k),...
            A,...
            B,...
            C);
    
    
        gamma_exp(k,1) = ...
            y_data(k)*P_mean / ...
            (x_data(k)*psat_exp(k,1));
    
    
        gamma_exp(k,2) = ...
            (1-y_data(k))*P_mean / ...
            ((1-x_data(k))*psat_exp(k,2));
    
    end


    %% Plot experiments
    plot(ax(1),x_data,T_data,...
        style.experimentalMarker,...
        "MarkerSize",style.markerSize,...
        "LineStyle",style.experimentalLine,...
        "LineWidth",2,...
        "Color",color,...
        "MarkerFaceColor",color,...
        "MarkerEdgeColor",'k',...
        "DisplayName", ...
        sprintf("Exp. %.2f kPa",P_mean/1000))


    plot(ax(1),y_data,T_data,...
        style.experimentalMarker,...
        "MarkerSize",style.markerSize,...
        "LineStyle",style.experimentalLine,...
        "LineWidth",2,...
        "Color",color,...
        "MarkerFaceColor",color,...
        "MarkerEdgeColor",'k',...
        "HandleVisibility","off")

    
    %% Plot experimental gamma
    plot(ax(j+1),x_data,gamma_exp(:,1),...
        style.experimentalMarker,...
        "MarkerSize",style.markerSize,...
        "LineStyle",style.experimentalLine,...
        "Color",color,...
        "MarkerFaceColor",color,...
        "MarkerEdgeColor",'k',...
        "HandleVisibility","off")
    
    
    plot(ax(j+1),x_data,gamma_exp(:,2),...
        style.experimentalMarker,...
        "MarkerSize",style.markerSize,...
        "LineStyle",style.experimentalLine,...
        "Color",color,...
        "MarkerFaceColor",[0.6 0.6 0.6],...
        "MarkerEdgeColor",'k',...
        "HandleVisibility","off")

    plot([0 1],[1 1],'k-','LineWidth',2)

end

legend(ax(1))

parts = split(string(selectedSystem.name),"_");
label = sprintf("%s(1) - %s(2)", parts(1), parts(2));

text(ax(1),0.5,0.96,label, ...
    "Units","normalized",...
    "FontSize",style.fontSize,...
    "HorizontalAlignment","center",...
    "FontWeight","bold");

for i = 2:numel(ax)
text(ax(i),0.5,0.94,...
    sprintf("Pressure %.2f kPa\nModel: %s", ...
    P_sets(i-1)/1000,...
    formatModelName(modelName)),...
    "Units","normalized",...
    "FontSize",style.fontSize,...
    "HorizontalAlignment","center",...
    "FontWeight","bold");
end



end